// Personnel data transcribed verbatim from the build spec §2.
// weekA / weekB tuples are [Mon, Tue, Wed, Thu, Fri], true = IN.

export type Weekday = "MON" | "TUE" | "WED" | "THU";
export type Specialty = "CARDIAC" | "GENERAL" | "NONE";

export interface ConsultantSeed {
  surname: string;
  specialty: Specialty;
  callProportion: number;
  employmentFraction: number;
  weekA: [boolean, boolean, boolean, boolean, boolean];
  weekB: [boolean, boolean, boolean, boolean, boolean];
  preferredDay: Weekday | null;
  secondaryDays: Weekday[];
  returnToWorkDate?: string;
  firstEligibleDate?: string;
  excludeFromBankHoliday?: boolean;
}

export const CONSULTANTS: ConsultantSeed[] = [
  // --- Cardiac (13) ---
  {
    surname: "Black",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, true, false, true],
    weekB: [true, true, true, false, false],
    preferredDay: "WED",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Coghlan",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, false, true, false, true],
    weekB: [false, false, true, true, true],
    preferredDay: "WED",
    secondaryDays: ["MON"],
  },
  {
    surname: "Cronly",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, true, false, false, true],
    weekB: [true, false, true, false, true],
    preferredDay: "MON",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Doyle",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, true, true, false],
    weekB: [false, true, false, true, true],
    preferredDay: "THU",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Ghent",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, false, false, true, true],
    weekB: [true, false, false, true, true],
    preferredDay: "THU",
    secondaryDays: ["MON"],
  },
  {
    surname: "Greaney",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, true, false, true, false],
    weekB: [false, true, false, true, true],
    preferredDay: "TUE",
    secondaryDays: ["THU"],
  },
  {
    surname: "Harte",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, false, true, true, true],
    weekB: [true, false, true, true, false],
    preferredDay: "THU",
    secondaryDays: ["WED"],
  },
  {
    surname: "Holt",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, false, true, true],
    weekB: [true, true, false, true, false],
    preferredDay: "TUE",
    secondaryDays: ["THU"],
    returnToWorkDate: "2027-07-01",
    firstEligibleDate: "2027-07-29",
    excludeFromBankHoliday: true,
  },
  {
    surname: "Kelecsenyi",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, true, true, false, false],
    weekB: [false, false, true, true, true],
    preferredDay: "WED",
    secondaryDays: ["MON", "THU"],
  },
  {
    surname: "Mislovic",
    specialty: "CARDIAC",
    callProportion: 0.8,
    employmentFraction: 0.8,
    weekA: [true, false, true, false, true],
    weekB: [true, true, true, false, false],
    preferredDay: "MON",
    secondaryDays: ["WED"],
  },
  {
    surname: "Nakhjavani",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, true, true, false],
    weekB: [false, false, true, true, true],
    preferredDay: "THU",
    secondaryDays: ["WED"],
  },
  {
    surname: "Prchalova",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, true, true, false, false],
    weekB: [false, true, true, false, true],
    preferredDay: "TUE",
    secondaryDays: ["WED"],
  },
  {
    surname: "Robinson",
    specialty: "CARDIAC",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, false, true, true, false],
    weekB: [true, false, true, false, true],
    preferredDay: "MON",
    secondaryDays: ["WED"],
  },

  // --- General (13) ---
  {
    surname: "Booley",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, false, true, true],
    weekB: [false, true, false, true, true],
    preferredDay: "THU",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Casby",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, true, true, false],
    weekB: [false, true, true, false, true],
    preferredDay: "WED",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Coleman",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, false, true, true],
    weekB: [true, true, false, true, false],
    preferredDay: "THU",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Fennessy",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, false, false, true, true],
    weekB: [true, true, false, true, false],
    preferredDay: "MON",
    secondaryDays: ["THU"],
  },
  {
    surname: "Gilmartin",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, false, true, true, false],
    weekB: [true, false, true, false, true],
    preferredDay: "WED",
    secondaryDays: ["MON"],
  },
  {
    surname: "Hoare",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, true, false, true],
    weekB: [false, true, true, false, true],
    preferredDay: "TUE",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Kong",
    specialty: "GENERAL",
    callProportion: 0.5,
    employmentFraction: 0.5,
    weekA: [true, false, true, true, false],
    weekB: [true, false, false, true, true],
    preferredDay: "MON",
    secondaryDays: ["THU"],
  },
  {
    surname: "Magee",
    specialty: "GENERAL",
    callProportion: 0.5,
    employmentFraction: 0.5,
    weekA: [true, false, true, true, false],
    weekB: [true, false, false, true, true],
    preferredDay: "MON",
    secondaryDays: ["THU"],
  },
  {
    surname: "Marshall",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, false, true, true],
    weekB: [true, true, false, true, false],
    preferredDay: "TUE",
    secondaryDays: ["THU"],
  },
  {
    surname: "Matthews",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [false, true, false, true, true],
    weekB: [false, true, false, false, true],
    preferredDay: "TUE",
    secondaryDays: [],
    returnToWorkDate: "2027-02-10",
    firstEligibleDate: "2027-03-10",
  },
  {
    surname: "Murphy",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, true, false, false, true],
    weekB: [true, true, true, false, false],
    preferredDay: "TUE",
    secondaryDays: ["MON"],
    returnToWorkDate: "2027-04-10",
    firstEligibleDate: "2027-05-08",
    excludeFromBankHoliday: true,
  },
  {
    surname: "Saviani",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, true, false, false, true],
    weekB: [true, true, false, true, false],
    preferredDay: "MON",
    secondaryDays: ["TUE"],
  },
  {
    surname: "Tierney",
    specialty: "GENERAL",
    callProportion: 1.0,
    employmentFraction: 1.0,
    weekA: [true, false, true, false, true],
    weekB: [true, false, true, false, true],
    preferredDay: "WED",
    secondaryDays: ["MON"],
  },

  // --- No on-call (proportion 0.0) ---
  {
    surname: "Mannion",
    specialty: "NONE",
    callProportion: 0.0,
    employmentFraction: 1.0,
    weekA: [false, false, false, false, false],
    weekB: [false, false, false, false, false],
    preferredDay: null,
    secondaryDays: [],
  },
  {
    surname: "McGinley",
    specialty: "NONE",
    callProportion: 0.0,
    employmentFraction: 0.8,
    weekA: [false, false, false, false, false],
    weekB: [false, false, false, false, false],
    preferredDay: null,
    secondaryDays: [],
  },
  {
    surname: "O'Hare",
    specialty: "NONE",
    callProportion: 0.0,
    employmentFraction: 1.0,
    weekA: [false, false, false, false, false],
    weekB: [false, false, false, false, false],
    preferredDay: null,
    secondaryDays: [],
  },
];
